[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --no-input"]

[start]
cmd = "python manage.py migrate --no-input && PYTHONPATH=. gunicorn van360sound.wsgi:application --bind 0.0.0.0:${PORT:-8000}"
