# Generated by Django 5.0.1 on 2026-01-11 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Leído')),
            ],
            options={
                'verbose_name': 'Mensaje de contacto',
                'verbose_name_plural': 'Mensajes de contacto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Headphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('driver_size', models.CharField(blank=True, max_length=50, verbose_name='Tamaño del driver')),
                ('frequency_response', models.CharField(blank=True, max_length=100, verbose_name='Respuesta de frecuencia')),
                ('impedance', models.CharField(blank=True, max_length=50, verbose_name='Impedancia')),
                ('sensitivity', models.CharField(blank=True, max_length=50, verbose_name='Sensibilidad')),
                ('battery_life', models.CharField(blank=True, max_length=100, verbose_name='Duración de batería')),
                ('connectivity', models.CharField(blank=True, max_length=100, verbose_name='Conectividad')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='headphones/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='headphones/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='headphones/')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headphones', to='blog.category')),
            ],
            options={
                'verbose_name': 'Auricular',
                'verbose_name_plural': 'Auriculares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('article_type', models.CharField(choices=[('analisis', 'Análisis'), ('novedad', 'Novedad'), ('guia', 'Guía'), ('comparativa', 'Comparativa')], default='analisis', max_length=20)),
                ('excerpt', models.TextField(max_length=300, verbose_name='Extracto')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('author', models.CharField(default='Van360Sound', max_length=100)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('views', models.IntegerField(default=0)),
                ('headphone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.headphone')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-published_date'],
            },
        ),
    ]
