# Generated by Django 5.0.1 on 2026-01-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headphone',
            name='amazon_link',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace Amazon'),
        ),
        migrations.AddField(
            model_name='headphone',
            name='ranking_order',
            field=models.IntegerField(default=0, verbose_name='Orden en Ranking'),
        ),
        migrations.AddField(
            model_name='headphone',
            name='score_accuracy',
            field=models.IntegerField(default=0, verbose_name='Precisión Acústica'),
        ),
        migrations.AddField(
            model_name='headphone',
            name='score_bass',
            field=models.IntegerField(default=0, verbose_name='Graves'),
        ),
        migrations.AddField(
            model_name='headphone',
            name='score_build',
            field=models.IntegerField(default=0, verbose_name='Calidad de Construcción'),
        ),
        migrations.AddField(
            model_name='headphone',
            name='score_comfort',
            field=models.IntegerField(default=0, verbose_name='Confort'),
        ),
        migrations.AddField(
            model_name='headphone',
            name='score_mids',
            field=models.IntegerField(default=0, verbose_name='Medios'),
        ),
        migrations.AddField(
            model_name='headphone',
            name='score_overall',
            field=models.IntegerField(default=0, verbose_name='Puntuación Global'),
        ),
        migrations.AddField(
            model_name='headphone',
            name='score_soundstage',
            field=models.IntegerField(default=0, verbose_name='Escenario Sonoro'),
        ),
        migrations.AddField(
            model_name='headphone',
            name='score_treble',
            field=models.IntegerField(default=0, verbose_name='Agudos'),
        ),
        migrations.AddField(
            model_name='headphone',
            name='score_value',
            field=models.IntegerField(default=0, verbose_name='Valor/Precio'),
        ),
    ]
