# Generated by Django 5.0.1 on 2026-01-17 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_headphone_amazon_link_headphone_ranking_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Nombre del autor')),
                ('author_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del autor')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Aprobado')),
                ('is_notified', models.BooleanField(default=False, verbose_name='Notificado por email')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-created_at'],
            },
        ),
    ]
