# Generated by Django 6.0.1 on 2026-01-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='headphone',
            name='show_price',
            field=models.BooleanField(default=True, verbose_name='Mostrar Precio'),
        ),
    ]
