# Generated by Django 6.0.1 on 2026-01-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_headphone_show_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='headphone',
            name='acoustic_design',
            field=models.CharField(blank=True, max_length=100, verbose_name='Diseño Acústico'),
        ),
    ]
