# Generated by Django 6.0.1 on 2026-01-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_headphone_acoustic_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='headphone',
            name='score_noise_cancelling',
            field=models.IntegerField(default=0, verbose_name='Cancelación de Ruido'),
        ),
    ]
