# Generated by Django 6.0.1 on 2026-01-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_headphone_score_noise_cancelling'),
    ]

    operations = [
        migrations.AddField(
            model_name='headphone',
            name='score_call_quality',
            field=models.IntegerField(default=0, verbose_name='Calidad de Llamadas'),
        ),
        migrations.AddField(
            model_name='headphone',
            name='score_transparency',
            field=models.IntegerField(default=0, verbose_name='Modo Transparencia'),
        ),
    ]
