# Generated by Django 6.0.1 on 2026-01-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_headphone_score_call_quality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headphone',
            name='show_review_button',
            field=models.BooleanField(default=True, verbose_name='Mostrar Botón de Análisis'),
        ),
    ]
