# Generated by Django 6.0.1 on 2026-01-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_headphone_show_review_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='headphone',
            name='official_link',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace Oficial'),
        ),
    ]
