# Generated by Django 6.0.1 on 2026-01-24 19:43

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_headphone_official_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headphone',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.headphone_directory_path, verbose_name='Imagen Secundaria 1'),
        ),
        migrations.AlterField(
            model_name='headphone',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.headphone_directory_path, verbose_name='Imagen Secundaria 2'),
        ),
        migrations.AlterField(
            model_name='headphone',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.headphone_directory_path, verbose_name='Imagen Principal'),
        ),
    ]
