# Generated by Django 6.0.1 on 2026-01-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_headphone_image_2_alter_headphone_image_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headphone',
            name='custom_review_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Enlace Personalizado de Review'),
        ),
    ]
