# Generated by Django 5.0.1 on 2026-02-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_category_seo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='headphone',
            name='protection_rating',
            field=models.CharField(blank=True, max_length=50, verbose_name='Grado de Protección (IP)'),
        ),
    ]
