# Generated by Django 6.0.2 on 2026-02-05 07:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_headphone_protection_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(help_text='Breve introducción de 1-2 frases que aparecerá en el listado del blog.', max_length=300, verbose_name='Resumen Breve'),
        ),
        migrations.AlterField(
            model_name='headphone',
            name='protection_rating',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Grado de Protección (IP)'),
        ),
    ]
