# Generated by Django 6.0.2 on 2026-03-02 06:53

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_comment_article_alter_comment_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Marca')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Logo de la Marca')),
                ('description', models.TextField(blank=True, help_text='Pequeño resumen que aparecerá en el listado.', verbose_name='Descripción Corta')),
                ('history', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Historia de la Marca')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sitio Web Oficial')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['name'],
            },
        ),
    ]
