# Generated by Django 6.0.2 on 2026-03-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.AddField(
            model_name='article',
            name='template',
            field=models.CharField(choices=[('default', 'Por defecto'), ('marcas', 'Plantilla Marcas (Imágenes centradas)')], default='default', max_length=20, verbose_name='Plantilla'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('analisis', 'Análisis'), ('novedad', 'Novedad'), ('guia', 'Guía'), ('comparativa', 'Comparativa'), ('marcas', 'Marcas')], default='analisis', max_length=20),
        ),
    ]
