# Generated by Django 5.0.4 on 2026-03-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_delete_brand_article_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='list_image',
            field=models.ImageField(blank=True, help_text='Logo o imagen simplificada exclusiva para listados exteriores. Si se deja en blanco, usará la imagen principal.', null=True, upload_to='articles/list/', verbose_name='Imagen/Logo (Portada)'),
        ),
        migrations.AddField(
            model_name='article',
            name='list_title',
            field=models.CharField(blank=True, help_text='Si se rellena, este título reemplazará al título principal únicamente en las cuadrículas y listados (útil para que solo ponga el nombre de la Marca).', max_length=200, null=True, verbose_name='Título Corto (Portada)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Imagen Principal (Interior)'),
        ),
    ]
