# Generated by Django 6.0.2 on 2026-03-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_article_list_image_article_list_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_fit',
            field=models.CharField(choices=[('contain', 'Mostrar entera (Sin recortes, puede dejar márgenes)'), ('cover', 'Llenar espacio (Recortada para llenar todo el marco sin márgenes)')], default='contain', help_text='Configura cómo se debe comportar la imagen en las tarjetas de la vista general.', max_length=20, verbose_name='Ajuste de Imagen (Portada)'),
        ),
    ]
