# Generated by Django 6.0.2 on 2026-03-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_article_image_fit'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_width',
            field=models.IntegerField(default=100, help_text='Porcentaje de ancho que ocupará la imagen (10-100). Útil para hacer más pequeños logos o recortar imágenes gigantes.', verbose_name='Ancho de la Imagen (%)'),
        ),
    ]
