# Generated by Django 6.0.2 on 2026-03-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_article_image_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_width_detail',
            field=models.IntegerField(default=100, help_text='Porcentaje de ancho que ocupará la imagen dentro del ARTÍCULO (10-100).', verbose_name='Ancho de la Imagen (%) (Interior)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_width',
            field=models.IntegerField(default=100, help_text='Porcentaje de ancho que ocupará la imagen en la PORTADA (10-100).', verbose_name='Ancho de la Imagen (%) (Portada)'),
        ),
    ]
