# Generated by Django 6.0.2 on 2026-04-07 10:59

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_article_image_width_detail_alter_article_image_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='WhatsApp / Teléfono')),
                ('date', models.DateField(verbose_name='Fecha de la Cita')),
                ('time', models.TimeField(verbose_name='Hora de la Cita')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de Confirmación'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada/No asistió'), ('completed', 'Completada')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True, verbose_name='ID de Pedido')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email del Cliente')),
                ('shipping_address', models.TextField(verbose_name='Dirección de Envío')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe Total')),
                ('status', models.CharField(choices=[('payment_pending', 'Pendiente de Pago'), ('paid', 'Pagado'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='payment_pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Descripción Detallada')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('stock', models.IntegerField(default=10, verbose_name='Stock Disponible')),
                ('main_image', models.ImageField(upload_to='products/', verbose_name='Imagen Principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='blog.category')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='blog.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.product')),
            ],
        ),
    ]
